### PR TITLE
[WIP] Add Gallery for Saving, Sharing, and Commenting on Models

### PR DESCRIPTION
**Pull request by zalo**
**[The Gallery Beta can be found Here!](https://cascade-studio-git-feat-gallery.zalo.vercel.app/Gallery)**

This adds a new section to the site (`/Gallery`) which acts as a place for users to share their models with other users to learn and grow from.

The functionality is a bit a rudimentary right now; once you've logged in from the main gallery page, you will see a button from the editor page that lets you upload your model to the Gallery itself.

Profile Management, Project Editing, and the Title/Description/Comments pane have not been implemented yet!  If you're a web developer, I would love your help!

### CODE REVIEW

**Comment by Irev-Dev** [comment]
Oh I didn't even see this PR hmm, sorry feel like I should have done due diligence with this one.

**Comment by zalo** [comment]
This PR is essentially obviated by @Irev-Dev 's excellent https://cadhub.xyz/

**Comment by Irev-Dev** [comment]
Let me know if you plan on deleting the branch @zalo, I'll make a copy first. I still have gotten around to cannibalising any of it.

**Comment by zalo** [comment]
(Branch restored 👍  )

**Comment by Irev-Dev** [comment]
I've got a copy, if you want to delete it again @zalo :)

**Pull request closed without merging**
